"use client";

import { ChangeEvent, FormEvent, useMemo, useState } from "react";

type Product = {
  title: string;
  category: "Festpreis" | "Auktion" | "Vormerkliste";
  price?: string;
  meta: string;
  accent: string;
  badge: string;
  description: string;
  productId?: string;
};

const products: Product[] = [
  { title: "2024 Topps Chrome UEFA Club Competitions Lamine Yamal RC #150", category: "Festpreis", price: "39,90 €", meta: "Demo · eBay synchronisiert · Sofort-Kaufen", accent: "gold", badge: "Demo-Angebot", description: "Topps Chrome UEFA Club Competitions · Rookie Card · Near Mint" },
  { title: "2023-24 Panini Prizm Premier League Bukayo Saka Silver #181", category: "Festpreis", price: "24,90 €", meta: "Demo · eBay synchronisiert · Sofort-Kaufen", accent: "red", badge: "Demo-Angebot", description: "Panini Prizm Premier League · Silver Prizm · Near Mint" },
  { title: "2022 Topps Finest Bundesliga Jamal Musiala Refractor #72", category: "Festpreis", price: "18,50 €", meta: "Demo · eBay synchronisiert · Sofort-Kaufen", accent: "blue", badge: "Demo-Angebot", description: "Topps Finest Bundesliga · Refractor · Near Mint" },
  { title: "2024 Panini Select FIFA Lamine Yamal Rookie /99", category: "Vormerkliste", meta: "Demo · Noch nicht im Verkauf", accent: "violet", badge: "Demo-Karte", description: "Sichere dir eine Nachricht, sobald diese Karte live geht." },
  { title: "2023-24 Topps Chrome Bundesliga Florian Wirtz Auto", category: "Auktion", meta: "Demo · Auktion auf eBay · endet bald", accent: "silver", badge: "eBay Auktion", description: "Nur als Hinweis im Webshop – der Kauf erfolgt direkt bei eBay." },
];

type Feedback = { type: "success" | "error"; message: string } | null;

function CardArtwork({ accent, index }: { accent: string; index: number }) {
  return <div className={`card-art card-art-${accent}`} aria-hidden="true"><span className="art-glow" /><span className="art-number">{String(index + 1).padStart(2, "0")}</span><span className="art-mark">BC</span><span className="art-lines" /><span className="art-label">TRADING<br />CARDS</span></div>;
}

function Field({ label, name, type = "text", required = true, placeholder }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string }) {
  return <label className="form-field"><span>{label}{required && <b aria-hidden="true"> *</b>}</span><input name={name} type={type} required={required} placeholder={placeholder} /></label>;
}

async function postForm(path: string, payload: Record<string, unknown>): Promise<string> {
  const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof data?.error?.message === "string" ? data.error.message : "Die Anfrage konnte nicht gesendet werden.");
  return "Danke! Deine Anfrage ist bei uns eingegangen. Wir melden uns per E-Mail.";
}

export default function Home() {
  const [activeFilter, setActiveFilter] = useState("Alle Angebote");
  const [query, setQuery] = useState("");
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [feedback, setFeedback] = useState<Record<string, Feedback>>({});
  const [loading, setLoading] = useState<string | null>(null);
  const [imageMetadata, setImageMetadata] = useState<Array<{ name: string; mimeType: string; size: number }>>([]);

  const filteredProducts = useMemo(() => products.filter((product) => (activeFilter === "Alle Angebote" || product.category === activeFilter) && product.title.toLowerCase().includes(query.toLowerCase())), [activeFilter, query]);

  async function submit(path: string, formId: string, event: FormEvent<HTMLFormElement>, payload: Record<string, unknown>) {
    event.preventDefault(); setFeedback((current) => ({ ...current, [formId]: null })); setLoading(formId);
    try { const message = await postForm(path, payload); setFeedback((current) => ({ ...current, [formId]: { type: "success", message } })); event.currentTarget.reset(); if (formId === "submission") setImageMetadata([]); }
    catch (error) { setFeedback((current) => ({ ...current, [formId]: { type: "error", message: error instanceof Error ? error.message : "Es ist ein Fehler aufgetreten." } })); }
    finally { setLoading(null); }
  }

  function handleImages(event: ChangeEvent<HTMLInputElement>) {
    const files = Array.from(event.target.files ?? []);
    setImageMetadata(files.map((file) => ({ name: file.name, mimeType: file.type, size: file.size })));
  }

  return <main>
    <div className="announcement"><span>✦</span> Versandkostenfrei ab 75 € innerhalb Deutschlands <span>→</span></div>
    <header className="site-header"><a className="brand" href="#top" aria-label="BrandyCards Startseite"><span className="brand-mark">B</span><span>BRANDY<span className="brand-red">CARDS</span><small>FOOTBALL COLLECTIBLES</small></span></a><nav className="main-nav" aria-label="Hauptnavigation"><a href="#shop">Shop</a><a href="#coming-soon">Demnächst</a><a href="#about">Über uns</a></nav><div className="header-actions"><button className="icon-button" aria-label="Suche" onClick={() => document.getElementById("search")?.focus()}>⌕</button><a className="account-link" href="#account">Konto <span>↗</span></a><button className="cart-button" aria-label="Warenkorb">Warenkorb <b>0</b></button></div></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">THE HOME OF FOOTBALL CARDS</p><h1>Cards with<br /><em>character.</em></h1><p className="hero-text">Ausgewählte Fußballkarten für Sammler. Persönlich ausgesucht, sicher verpackt und mit Liebe zum Detail.</p><div className="hero-actions"><a className="button button-primary" href="#shop">Kollektion entdecken <span>↘</span></a><a className="text-link" href="#about">Mehr über BrandyCards <span>→</span></a></div></div><div className="hero-art" aria-label="Abstrakte Darstellung einer Premium-Sammelkarte"><div className="hero-card hero-card-back"><span>BRANDY<br />CARDS</span></div><div className="hero-card hero-card-front"><div className="hero-card-top">BRANDYCARDS <span>01 / 01</span></div><div className="hero-player">BC</div><div className="hero-card-bottom"><strong>THE<br />COLLECTOR&apos;S<br />CHOICE</strong><span>LEVERKUSEN<br />GERMANY</span></div></div><span className="hero-stamp">EST.<br /><strong>2024</strong></span></div></section>
    <section className="ticker" aria-label="BrandyCards Werte"><span>AUTHENTIC CARDS</span><i>✦</i><span>FAIR PRICES</span><i>✦</i><span>FAST SHIPPING</span><i>✦</i><span>MADE FOR COLLECTORS</span></section>
    <section className="shop-section" id="shop"><div className="section-heading"><div><p className="eyebrow">CURATED FOR YOU</p><h2>Aktuelle Karten</h2></div><p>Demo-Ansicht. Die echten eBay-Angebote werden regelmäßig in den Webshop übertragen.</p></div><div className="shop-toolbar"><div className="filter-tabs">{["Alle Angebote", "Festpreis", "Auktion", "Vormerkliste"].map((filter) => <button key={filter} className={activeFilter === filter ? "active" : ""} onClick={() => setActiveFilter(filter)}>{filter}</button>)}</div><label className="search-field" htmlFor="search"><span>⌕</span><input id="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Spieler, Set oder Kartennummer" aria-label="Karten durchsuchen" /></label></div><div className="product-grid">{filteredProducts.map((product, index) => <article className="product-card" key={product.title}><div className="product-image"><CardArtwork accent={product.accent} index={index} /><span className="product-badge">{product.badge}</span><button className="heart" aria-label={`${product.title} merken`}>♡</button></div><div className="product-info"><p className="product-meta">{product.meta}</p><h3>{product.title}</h3><p className="product-description">{product.description}</p><div className="product-footer">{product.price ? <strong>{product.price}</strong> : <strong className="interest-price">Interesse bekunden</strong>}{product.category === "Auktion" ? <a className="product-cta ebay" href="https://www.ebay.de/str/brandycards" target="_blank" rel="noreferrer">Auf eBay ansehen ↗</a> : product.category === "Vormerkliste" ? <button className="product-cta" onClick={() => setSelectedProduct(product)}>Vormerken <span>→</span></button> : <button className="product-cta" disabled title="Warenkorb folgt">Demo · bald verfügbar <span>+</span></button>}</div></div></article>)}</div>{filteredProducts.length === 0 && <div className="empty-state">Keine Karten für diese Suche gefunden.</div>}<div className="center-action"><a className="button button-outline" href="#shop">Alle Angebote ansehen <span>↘</span></a></div></section>
    <section className="split-section" id="coming-soon"><div className="split-copy"><p className="eyebrow">NOT ON SALE. YET.</p><h2>Deine Wunschkarte<br /><em>könnte hier sein.</em></h2><p>Manche Karten sind schon in unserer Sammlung, aber noch nicht im Verkauf. Hinterlasse dein Interesse – wir melden uns, sobald sie verfügbar ist.</p><a className="button button-primary" href="#inquiry">Karte anfragen <span>↘</span></a></div><div className="split-panel"><div className="panel-card"><span>COMING<br />SOON</span><b>✦</b></div><div className="panel-note">Nur Titel. Kein Overhead.<br /><strong>Einfach Interesse zeigen.</strong></div></div></section>
    {selectedProduct && <section className="form-section compact-form" aria-labelledby="interest-title"><div className="form-heading"><p className="eyebrow">VORMERKEN</p><h2 id="interest-title">{selectedProduct.title}</h2><p>Die Demo-Karte hat noch keine echte Produkt-ID. Die Vormerkung wird nach dem eBay-Import aktiv.</p></div><form onSubmit={(event) => { event.preventDefault(); setFeedback((current) => ({ ...current, interest: { type: "error", message: "Diese Demo-Karte ist noch nicht mit der Produktdatenbank verbunden." } })); }}><Field label="E-Mail-Adresse" name="email" type="email" /><button className="button button-primary" type="submit">Vormerkung senden</button>{feedback.interest && <p className={`form-feedback ${feedback.interest.type}`} role="status">{feedback.interest.message}</p>}</form></section>}
    <section className="service-section" id="inquiry"><div className="service-card"><span className="service-icon">↗</span><p className="eyebrow">DU SUCHST ETWAS BESTIMMTES?</p><h2>Wir helfen beim Finden.</h2><p>Schreib uns, welche Karte du suchst. Auch ohne Kundenkonto – nur deine E-Mail-Adresse genügt.</p><a href="#contact-form" className="text-link">Karte anfragen <span>→</span></a></div><div className="service-card service-card-dark"><span className="service-icon">＋</span><p className="eyebrow">DEINE KARTEN. DEINE CHANCE.</p><h2>Verkaufe an BrandyCards.</h2><p>Du möchtest deine Karten anbieten? Schick uns Bilder und optional deine Preisvorstellung.</p><a href="#sell" className="text-link">Karten anbieten <span>→</span></a></div></section>
    <section className="forms-section" id="contact-form"><div className="form-card"><p className="eyebrow">KONTAKT</p><h2>Karte anfragen</h2><p>Du suchst eine bestimmte Karte? Sende uns Titel, Nachricht und E-Mail-Adresse.</p><form onSubmit={(event) => { const data = new FormData(event.currentTarget); return submit("/api/inquiries", "inquiry", event, { title: data.get("title"), message: data.get("message"), email: data.get("email") }); }}><Field label="Kartentitel" name="title" placeholder="z. B. 2024 Topps Chrome …" /><label className="form-field"><span>Nachricht *</span><textarea name="message" required maxLength={4000} rows={4} placeholder="Wonach suchst du?" /></label><Field label="E-Mail-Adresse" name="email" type="email" /><button className="button button-primary" type="submit" disabled={loading === "inquiry"}>{loading === "inquiry" ? "Wird gesendet …" : "Anfrage senden"}</button>{feedback.inquiry && <p className={`form-feedback ${feedback.inquiry.type}`} role="status">{feedback.inquiry.message}</p>}</form></div><div className="form-card" id="sell"><p className="eyebrow">ANKAUF</p><h2>Eigene Karten anbieten</h2><p>Bilder werden aktuell noch nicht hochgeladen. Wir speichern zunächst nur die von dir ausgewählten Bild-Metadaten.</p><form onSubmit={(event) => { const data = new FormData(event.currentTarget); return submit("/api/card-submissions", "submission", event, { title: data.get("title"), price: data.get("price") || undefined, message: data.get("message") || undefined, email: data.get("email"), images: imageMetadata }); }}><Field label="Kartentitel" name="title" /><Field label="Gewünschter Preis in €" name="price" type="number" required={false} placeholder="Optional" /><label className="form-field"><span>Nachricht</span><textarea name="message" maxLength={4000} rows={4} placeholder="Zustand, Anzahl oder weitere Hinweise" /></label><Field label="E-Mail-Adresse" name="email" type="email" /><label className="form-field"><span>Bilder auswählen <small>(sichere Uploads folgen)</small></span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={handleImages} /><small>{imageMetadata.length ? `${imageMetadata.length} Bild-Metadaten vorgemerkt – keine Datei wurde hochgeladen.` : "Noch keine Bild-Metadaten ausgewählt."}</small></label><button className="button button-primary" type="submit" disabled={loading === "submission"}>{loading === "submission" ? "Wird gesendet …" : "Karte anbieten"}</button>{feedback.submission && <p className={`form-feedback ${feedback.submission.type}`} role="status">{feedback.submission.message}</p>}</form></div></section>
    <section className="offer-section"><div className="form-card"><p className="eyebrow">PREISVORSCHLAG</p><h2>Interesse an einer Karte?</h2><p>Preisvorschläge werden nach dem eBay-Import für echte Produktkarten freigeschaltet. Demo-Karten können noch nicht verbindlich angeboten werden.</p><form onSubmit={(event) => { event.preventDefault(); setFeedback((current) => ({ ...current, offer: { type: "error", message: "Demo-Karten sind noch nicht mit der Produktdatenbank verbunden." } })); }}><Field label="Kartentitel" name="title" /><Field label="Dein Preis in €" name="price" type="number" /><label className="form-field"><span>Nachricht</span><textarea name="message" rows={3} placeholder="Optional" /></label><Field label="E-Mail-Adresse" name="email" type="email" /><button className="button button-primary" type="submit">Preisvorschlag senden</button>{feedback.offer && <p className={`form-feedback ${feedback.offer.type}`} role="status">{feedback.offer.message}</p>}</form></div></section>
    <section className="about-section" id="about"><p className="eyebrow">FROM LEVERKUSEN, WITH PASSION</p><h2>Für Karten, die<br /><em>mehr erzählen.</em></h2><p>BrandyCards ist ein Familienprojekt von zwei Brüdern. Wir sammeln, handeln und teilen die Begeisterung für Fußballkarten – ehrlich, persönlich und mit einem Auge fürs Detail.</p><div className="about-signature">B<span>×</span>B <small>BRÜDER · BRANDY · BALL</small></div></section>
    <footer id="contact"><div className="footer-top"><a className="brand" href="#top"><span className="brand-mark">B</span><span>BRANDY<span className="brand-red">CARDS</span><small>FOOTBALL COLLECTIBLES</small></span></a><p>Collect the moment.</p><div className="footer-links"><a href="#account">Konto</a><a href="#contact-form">Kontakt</a><a href="#contact">Instagram ↗</a></div></div><div className="footer-bottom"><span>© 2026 BrandyCards · Leverkusen</span><span>Impressum &nbsp; Datenschutz</span><span>Designed for collectors</span></div></footer>
  </main>;
}
